name: Commit History to JSON to Pages Branch
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      REPO: ${{ secrets.REPO }}
      USER: ${{ secrets.USER }}
      
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install requests
        run: |
          pip install requests
          pip install python-dotenv

      - name: Run the script and generate JSON
        run: |
          python to-json.py

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages # Checkout 'gh-pages' branch to 'gh-pages' directory

      - name: Copy file to gh-pages branch
        run: |
          cp demofile.json gh-pages/

      - name: Commit and Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          directory: .
          commit_message: "Update demofile.json"
